<a href="https://colab.research.google.com/github/Bkalene/exercicios-python/blob/main/Trabalho_Matem%C3%A1tica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Calcular Matriz Inversa - Grupo: Andreza, Brisa e Tales**

## **Sem as bibliotecas do Python**


In [ ]:
# Função para calcular o cofator
def Calc_Cofator(matriz, cofatores, l, c, n): #Calcula o cofator da matriz, localizada na linha "l"
    i = 0                                     # coluna "c", e salvando o resultado em 'resultado'.
    j = 0                                     # 'n' é a ordem da matriz, que dá o número de iterações nos FOR
    for row in range(n):   #FOR da linha
        for col in range(n):  #FOR da coluna
            if (row != l and col != c):
                cofatores[i][j] = matriz[row][col]  #Resultado em relação ao calculo do cofator
                j += 1
                if j == n - 1:
                    j = 0
                    i += 1

# Função para calcular o determinante
def Calc_Determinante(matriz, n):  #Calculo do determinante.
    D = 0
    if n == 1:
        return matriz[0][0]
    cofatores = [[0]*n for _ in range(n)] #inicia os calculos dos determinantes
    sinal = 1    #variável sinal alterna os seiais nos calculos dos determinantes
    for f in range(n):
        Calc_Cofator(matriz, cofatores, 0, f, n)
        D += sinal * matriz[0][f] * Calc_Determinante(cofatores, n - 1)
        sinal = -sinal
    return D

# Função para calcular e armazenar os cofatores
def Calc_Transposta(matriz, transposta, N):
    if N == 1:
        transposta[0][0] = 1
        return
    sinal = 1
    cofatores = [[0]*N for _ in range(N)]
    for i in range(N):
        for j in range(N):
            Calc_Cofator(matriz, cofatores, i, j, N)
            sinal = 1 if ((i+j)%2==0) else -1  #regra do sinal:  Se a soma de i e j for par, o sinal é positivo (1), caso contrário, é negativo (-1) - (-1).i+j
            transposta[j][i] = sinal*Calc_Determinante(cofatores, N-1)

# Função para calcular a inversa
def Calc_Inversa(matriz, N):
    if len(matriz) != len(matriz[0]):
        raise ValueError("A matriz deve ser quadrada para calcular a inversa.") #verifica se é uma matriz quadrada
    det = Calc_Determinante(matriz, N)
    if det == 0:
        raise ValueError("A matriz é singular (Det = 0), portanto, não tem inversa.")
    transposta = [[0]*N for _ in range(N)] #cria uma matriz transposta formada por 0, na mesma ordem da matriz original
    Calc_Transposta(matriz, transposta, N)
    for i in range(N):
        for j in range(N):
            matriz[i][j] = transposta[i][j]/float(det)
    print("Matriz inversa:")
    for row in matriz:
        print(row)
    print()

###**Exemplos**

In [ ]:
# Matriz de entrada
mat = [[1, 0, 0], [1, 0, 1], [0, 1, 1]]
N = len(mat)

# Calculando a inversa
Calc_Inversa(mat, N)

Matriz inversa:
[1.0, -0.0, -0.0]
[1.0, -1.0, 1.0]
[-1.0, 1.0, -0.0]



In [ ]:
# Matriz de entrada
mat = [[1,0,0], [1,0,1], [1,0,2]]
N = len(mat)

# Calculando a inversa
Calc_Inversa(mat, N)

ValueError: ignored

In [ ]:
# Matriz de entrada
mat = [[1,0], [1,0], [1,0]]
N = len(mat)

# Calculando a inversa
Calc_Inversa(mat, N)

ValueError: ignored

**Função Calc_Cofator:** Esta função calcula o cofator de um elemento específico em uma matriz. O cofator é o determinante da submatriz que é formada removendo a linha e a coluna do elemento especificado, multiplicado por (-1) elevado à soma dos índices de linha e coluna.

**Função Calc_Determinante:** Esta função calcula o determinante de uma matriz. Se a matriz é 1x1, o determinante é simplesmente o único elemento. Caso contrário, a função calcula o determinante através da expansão dos cofatores. Multiplica cada elemento da primeira linha pelo cofator correspondente e soma esses valores para obter o determinante.

**Função Calc_Transposta:** Esta função calcula a matriz adjunta de uma matriz, que é a transposta da matriz de cofatores. Para cada elemento da matriz, calcula o cofator correspondente e armazena o valor transposto na matriz adjunta.

**Função Calc_Ibersa:** Esta função calcula a inversa de uma matriz. Primeiro, verifica se a matriz é singular (ou seja, se seu determinante é zero), caso em que a matriz não tem inversa. Em seguida, calcula a matriz adjunta e divide cada elemento pela determinante para obter a matriz inversa.

## **Erros que podem ocorrer**

**Matriz não quadrada:** Apenas matrizes quadradas (ou seja, matrizes com o mesmo número de linhas e colunas) têm uma inversa. Se você tentar calcular a inversa de uma matriz que não seja quadrada, receberá um erro.

**Matriz singular:** Uma matriz é chamada de "singular" se seu determinante for zero. Matrizes singulares não têm uma inversa. Se você tentar calcular a inversa de uma matriz singular, o denominador na fórmula da inversa será zero, o que levará a uma divisão por zero.


## **Com as bibliotecas do Python**

In [ ]:
import numpy as np

# Defina sua matriz de ordem 3
matriz = np.array([[1, 1, 0],
                   [0, 1, 1],
                   [1, 0, 2]])

# Calcule a determinante da matriz original
determinante = np.linalg.det(matriz)

# Calcule a matriz dos cofatores
cofatores = np.linalg.inv(matriz).T * determinante

# Calcule a matriz inversa
matriz_inversa = np.linalg.inv(matriz)

# Calcule a matriz transposta
matriz_transposta = cofatores.T

# Imprima a matriz original, a determinante, a matriz dos cofatores, a matriz inversa e a matriz transposta
print("Matriz Original:")
print(matriz)

print(f"\nDeterminante da Matriz Original: {determinante:.1f}")

print("\nMatriz dos Cofatores:")
print(cofatores)

print("\nMatriz Transposta(Adjunta):")
print(matriz_transposta)

print("\nMatriz Inversa:")
print(matriz_inversa)

Matriz Original:
[[1 1 0]
 [0 1 1]
 [1 0 2]]

Determinante da Matriz Original: 3.0

Matriz dos Cofatores:
[[ 2.  1. -1.]
 [-2.  2.  1.]
 [ 1. -1.  1.]]

Matriz Transposta(Adjunta):
[[ 2. -2.  1.]
 [ 1.  2. -1.]
 [-1.  1.  1.]]

Matriz Inversa:
[[ 0.66666667 -0.66666667  0.33333333]
 [ 0.33333333  0.66666667 -0.33333333]
 [-0.33333333  0.33333333  0.33333333]]


**SciPy:**
A biblioteca SciPy é construída sobre o NumPy e fornece recursos adicionais, incluindo módulos específicos para álgebra linear (scipy.linalg). Ela oferece funcionalidades avançadas, como decomposições, sistemas lineares, entre outros.

**SymPy **
É uma biblioteca para matemática simbólica em Python. Embora não seja tão otimizada para cálculos numéricos quanto o NumPy, ela pode ser útil para manipulações simbólicas e cálculos algébricos.

**Matplotlib:**
Enquanto o Matplotlib é conhecido principalmente por criar gráficos, ele também possui alguns módulos para trabalhar com matrizes, como o matplotlib.cbook.

**TensorFlow e PyTorch:**
Essas são bibliotecas de aprendizado de máquina, mas também incluem funcionalidades para trabalhar com tensores (matrizes multidimensionais) de forma eficiente. São muito utilizadas em redes neurais e aprendizado profundo.